export const CONSTANT_VALUE = {
  WELCOME: 'Welcome',
  REC_EVENTS: 'Recommended Events',
  ALL_EVENTS: 'All Events',
  FRIENDS: ' friends',
  PARTNERED: 'Partnered',
  TOTAL_PRICE: 'Total Price:',
  EVENT_CREATOR: 'Event Creator:',
  STEAVE_JOBS: 'Steve Jobs',
  RESERVE: '2020 Are You In app. All rights reserved',
  SHARE_EVENT: 'Share Event',
  ATTENDING: 'attending',
  ABOUT: 'ABOUT :',
  LOCATION: 'Location :',
  TAKE_ME_THERE: 'Take me there',
  CONTACT: 'Contact :',
  SEND_EMAIL: 'Send us an email at',
  EMAIL_ID: 'contact@techalchemy.co',
  CALL_NUM: 'or call us at +1 991-681-0200',
  PURCHASE_SUCCESS: 'Purchase Success',
  THANK_YOU: 'Thank you!',
  PAYMENT_SUCCESS: ' Your payment was made successfully!',
  BOOKING_ID: 'Your booking ID',
  CONTENT: `You will need this booking ID to enter inside the event. You can
  view this code inside your profile / booked events`,
  CLOSE: 'Close',
  LOCATION_URL:
    'http://api.positionstack.com/v1/forward?access_key=81f2cbab5535951fe844607ead12aad2&query=',
};
